import React from "react"
// let items = [
//   {
//     menuName: "Dinner",
//     menuItems: [
//       {
//         "itemId": 1,
//         "itemPrice": "12",
//         "itemName": "Lasagne",
//         "itemDescription": "Meat and cheese layered between house-made pasta with bell peppers and onions."
//       },
//       {
//         "itemId": 2,
//         "itemPrice": "10",
//         "itemName": "Cheese Ravioli",
//         "itemDescription": "Cheese-filled ravioli served with house red sauce."
//       },
//       {
//         "itemId": 3,
//         "itemPrice": "14",
//         "itemName": "Chicken Parmesan",
//         "itemDescription": "Breaded chicken topped with marinara sauce and lots of cheese served over house made spaghetti."
//       }
//     ]
//   },
//   {
//     menuName: "Dessert",
//     menuItems: [
//       {
//         "itemId": 45,
//         "itemPrice": "10",
//         "itemName": "Chocolate Lava Cake",
//         "itemDescription": "Dark chocolate molten lava cake. Serves 2-3."
//       },
//       {
//         "itemId": 47,
//         "itemPrice": "8",
//         "itemName": "Tiramisu",
//         "itemDescription": "Layers of espresso-soaked ladyfingers and marscarpone cream topped with cocoa and espresso powder."
//       },
//       {
//         "itemId": 49,
//         "itemPrice": "5",
//         "itemName": "Cannolis",
//         "itemDescription": "Three flaky pastries enclosing a rich, ricotta filling dotted with decadent chocolate chips."
//       },
//       {
//         "itemId": 50,
//         "itemPrice": "5",
//         "itemName": "Cappuccino",
//         "itemDescription": "Steamed milk with two ristretto shots of espresso."
//       }
//     ]
//   }
// ]

const items = [{
  "itemId": 1,
  "itemPrice": "12",
  "itemName": "Lasagne",
  "itemDescription": "Meat and cheese layered between house-made pasta with bell peppers and onions."
},
// {
//   "itemId": 2,
//   "itemPrice": "10",
//   "itemName": "Cheese Ravioli",
//   "itemDescription": "Cheese-filled ravioli served with house red sauce."
// },
]
console.log("item:", items[0].itemName);
// Assume that an object is passed in and assigned to the props variable with the following properties:

// {
//         "itemId": 1,
//         "itemPrice": "12",
//         "itemName": "Lasagne",
//         "itemDescription": "Meat and cheese layered between house-made pasta with bell peppers and onions."
// }
// These are made available on the props object for access in the render method.

// The render method then must return JSX that represents the HTML that is generated by the component.

// We start by creating the MenuItem class and the render method that renders just one property on the props object:

// in: src/components/MenuItem/index.js:
const MenuItem = ({items}) => {
return(
       <div>
          <h1>{items.itemName}</h1>
          {/* <p>test</p> */}
       </div>
);
}

export default MenuItem;

// Note for class component :

// We do not need to explicitly assign the props value because the React.Component class will do this for us.

// We can skip the constructor because we are not initializing any values or state or performing any setup actions.