import React from "react"

// // const items = [{
// //   // item 1
// //   "itemId": 1,
// //   "itemPrice": "12",
// //   "itemName": "Lasagne",
// //   "itemDescription": "Meat and cheese layered between house-made pasta with bell peppers and onions."
// // },
// // // item 2
// // // {
// // //   "itemId": 2,
// // //   "itemPrice": "10",
// // //   "itemName": "Cheese Ravioli",
// // //   "itemDescription": "Cheese-filled ravioli served with house red sauce."
// // // },
// ]
// console.log("item:", items[0].menuItems[0].itemName, ",",
//   items[0].menuItems[1].itemName
// );
// // Assume that an object is passed in and assigned to the props variable with the following properties:

// {
//         "itemId": 1,
//         "itemPrice": "12",
//         "itemName": "Lasagne",
//         "itemDescription": "Meat and cheese layered between house-made pasta with bell peppers and onions."
// }
// These are made available on the props object for access in the render method.

// The render method then must return JSX that represents the HTML that is generated by the component.

// We start by creating the MenuItem class and the render method that renders just one property on the props object:

// in: src/components/MenuItem/index.js:]
const MenuItem = ({items}) => {
   // console.log({...this.props.items})
   // console.log("items = ",items.itemName)
return(
      <div>
         <p>${items.itemPrice}</p>
         <h2>{items.itemName}</h2>
         <p>{items.itemDescription}</p>
         <button>Add to Cart</button>
      </div>
);
}

export default MenuItem;

// Note for class component :

// We do not need to explicitly assign the props value because the React.Component class will do this for us.

// We can skip the constructor because we are not initializing any values or state or performing any setup actions.